### ISSUE TITLE
The quick start does not compile

### ISSUE THREAD

**Issue by luistrigueiros** [netifi/proteus-spring-quickstart#3]
λ gradle build
Starting a Gradle Daemon, 3 busy and 1 incompatible and 1 stopped Daemons could not be reused, use --status for details
> Task :service-idl:extractIncludeProto FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':service-idl:compile'.
> Could not find io.rsocket.rpc:rsocket-rpc-core:0.2.0.
  Searched in the following locations:
    - https://jcenter.bintray.com/io/rsocket/rpc/rsocket-rpc-core/0.2.0/rsocket-rpc-core-0.2.0.pom
    - https://jcenter.bintray.com/io/rsocket/rpc/rsocket-rpc-core/0.2.0/rsocket-rpc-core-0.2.0.jar
    - https://dl.bintray.com/netifi/netifi-oss/io/rsocket/rpc/rsocket-rpc-core/0.2.0/rsocket-rpc-core-0.2.0.pom
    - https://dl.bintray.com/netifi/netifi-oss/io/rsocket/rpc/rsocket-rpc-core/0.2.0/rsocket-rpc-core-0.2.0.jar
  Required by:
      project :service-idl

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

**Comment by Petikoch** [comment]
Same here @robertroeser, trying https://www.netifi.com/getstarted-springboot to "see the magic!" :-)

```
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ':client:bootJar'.
> Could not resolve all task dependencies for configuration ':client:runtimeClasspath'.
   > Could not find io.rsocket.rpc:rsocket-rpc-core:0.2.0.
     Required by:
         project :client > project :service-idl > io.netifi.proteus:proteus-client:0.9.0
```

**Comment by robertroeser** [comment]
@Petikoch @luistrigueiros we have an issue with are repository because we moved the rpc to the open source project. I have pushed a change to master that will fix this temporary until we do our release which is coming very soon. Sorry for the inconvenience.

**Comment by Petikoch** [comment]
@robertroeser 

I just tried it again... now there is a different issue:

```
Starting a Gradle Daemon (subsequent builds will be faster)
> Task :service-idl:extractIncludeProto
> Task :service-idl:extractProto
> Task :service-idl:generateProto FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Could not resolve all files for configuration ':service-idl:protobufToolsLocator                                                                                                                                            _rsocketRpc'.
> Could not find rsocket-rpc-protobuf-windows-x86_64.exe (io.rsocket.rpc:rsocket                                                                                                                                            -rpc-protobuf:0.2.2).
  Searched in the following locations:
      https://jcenter.bintray.com/io/rsocket/rpc/rsocket-rpc-protobuf/0.2.2/rsoc                                                                                                                                            ket-rpc-protobuf-0.2.2-windows-x86_64.exe

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug                                                                                                                                             option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 1m 22s
3 actionable tasks: 3 executed
```

**Comment by robertroeser** [comment]
@kbahr kyle do you know anything about the windows binary?

**Comment by kbahr** [comment]
Indeed we did lose the 0.2.2 binaries in the repository shuffle. We're in the process of releasing a new version of the Quickstart that depends on 0.2.4 binaries which I've released (and tested the release candidate of the Quickstart). We're going through final validation testing now and I will follow up when this should be fixed for you guys.

**Comment by kbahr** [comment]
@luistrigueiros @Petikoch This should be resolved now.

**Comment by Petikoch** [comment]
@kbahr It's fine now :-)

**Comment by kbahr** [comment]
Thanks for confirming @Petikoch
